/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AuthUserService } from "../authUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthUserCreateInput } from "./AuthUserCreateInput";
import { AuthUser } from "./AuthUser";
import { AuthUserFindManyArgs } from "./AuthUserFindManyArgs";
import { AuthUserWhereUniqueInput } from "./AuthUserWhereUniqueInput";
import { AuthUserUpdateInput } from "./AuthUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuthUserControllerBase {
  constructor(
    protected readonly service: AuthUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AuthUser })
  @nestAccessControl.UseRoles({
    resource: "AuthUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAuthUser(
    @common.Body() data: AuthUserCreateInput
  ): Promise<AuthUser> {
    return await this.service.createAuthUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        isActive: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AuthUser] })
  @ApiNestedQuery(AuthUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AuthUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authUsers(@common.Req() request: Request): Promise<AuthUser[]> {
    const args = plainToClass(AuthUserFindManyArgs, request.query);
    return this.service.authUsers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        isActive: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AuthUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authUser(
    @common.Param() params: AuthUserWhereUniqueInput
  ): Promise<AuthUser | null> {
    const result = await this.service.authUser({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        isActive: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AuthUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAuthUser(
    @common.Param() params: AuthUserWhereUniqueInput,
    @common.Body() data: AuthUserUpdateInput
  ): Promise<AuthUser | null> {
    try {
      return await this.service.updateAuthUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          isActive: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AuthUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAuthUser(
    @common.Param() params: AuthUserWhereUniqueInput
  ): Promise<AuthUser | null> {
    try {
      return await this.service.deleteAuthUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          isActive: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
